name: nextjs CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: npm install
        run: npm install
      - name: Build
        run: npm run build
      # - name: Restart PM2
      #   run: pm2 restart 0
      # - name: Start server
      #   run: npm run start
      

